package xyz.jpenilla.squaremap.common.data;

import it.unimi.dsi.fastutil.objects.Reference2IntMap;
import it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap;
import it.unimi.dsi.fastutil.objects.Reference2ObjectMap;
import it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.framework.qual.DefaultQualifier;
import xyz.jpenilla.squaremap.common.Logging;

/**
 * Meridian: the average colour of each block's top face, taken from the vanilla textures
 * (generated by tools/gen_block_colors.py into squaremap/block_colors.txt).
 * Blocks the game tints by biome are stored as their grey texture colour plus the kind of tint.
 */
@DefaultQualifier(NonNull.class)
public final class TextureColors {
    public enum Tint { GRASS, FOLIAGE, WATER }

    private static @Nullable TextureColors instance;

    private final Reference2IntMap<Block> colors = new Reference2IntOpenHashMap<>();
    private final Reference2ObjectMap<Block, Tint> tints = new Reference2ObjectOpenHashMap<>();

    private TextureColors() {
        this.colors.defaultReturnValue(-1);
        try (final @Nullable InputStream in = TextureColors.class.getResourceAsStream("/squaremap/block_colors.txt")) {
            if (in == null) {
                Logging.logger().warn("squaremap/block_colors.txt is missing; using map palette colours");
                return;
            }
            final BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }
                final String[] parts = line.split(" ");
                final @Nullable Identifier id = Identifier.tryParse(parts[0]);
                if (id == null || parts.length < 2) {
                    continue;
                }
                final @Nullable Block block = BuiltInRegistries.BLOCK.getOptional(id).orElse(null);
                if (block == null) {
                    continue;
                }
                this.colors.put(block, 0xFF000000 | Integer.parseInt(parts[1], 16));
                if (parts.length > 2) {
                    switch (parts[2]) {
                        case "grass" -> this.tints.put(block, Tint.GRASS);
                        case "foliage" -> this.tints.put(block, Tint.FOLIAGE);
                        case "water" -> this.tints.put(block, Tint.WATER);
                        default -> {
                        }
                    }
                }
            }
        } catch (final IOException | RuntimeException e) {
            Logging.logger().warn("Could not read block texture colours; using map palette colours", e);
        }
    }

    public static synchronized TextureColors get() {
        if (instance == null) {
            instance = new TextureColors();
        }
        return instance;
    }

    /** The block's texture colour, or -1 if it has none. */
    public int color(final Block block) {
        return this.colors.getInt(block);
    }

    public @Nullable Tint tint(final Block block) {
        return this.tints.get(block);
    }
}
